
block_BLITCON_offs			:=	CS_BLIT_BLITCON_offs-CS_BLIT_base
block_FUNCGEN_offs			:=	CS_BLIT_FUNCGEN_offs-CS_BLIT_base
block_MASK_FIRST_offs		:=	CS_BLIT_MASK_FIRST_offs-CS_BLIT_base
block_MASK_LAST_offs		:=	CS_BLIT_MASK_LAST_offs-CS_BLIT_base
block_WIDTH_offs			:=	CS_BLIT_WIDTH_offs-CS_BLIT_base
block_HEIGHT_offs			:=	CS_BLIT_HEIGHT_offs-CS_BLIT_base
block_SHIFT_A_offs			:=	CS_BLIT_SHIFT_A_offs-CS_BLIT_base
block_STRIDE_A_offs			:=	CS_BLIT_STRIDE_A_offs-CS_BLIT_base
block_STRIDE_B_offs			:=	CS_BLIT_STRIDE_B_offs-CS_BLIT_base
block_STRIDE_C_offs			:=	CS_BLIT_STRIDE_C_offs-CS_BLIT_base
block_ADDR_A_offs			:=	CS_BLIT_ADDR_A_offs-CS_BLIT_base
block_DATA_A_offs			:=	CS_BLIT_DATA_A_offs-CS_BLIT_base
block_ADDR_B_offs			:=	CS_BLIT_ADDR_B_offs-CS_BLIT_base
block_DATA_B_offs			:=	CS_BLIT_DATA_B_offs-CS_BLIT_base
block_ADDR_C_offs			:=	CS_BLIT_ADDR_C_offs-CS_BLIT_base
block_DATA_C_offs			:=	CS_BLIT_DATA_C_offs-CS_BLIT_base
block_ADDR_E_offs			:=	CS_BLIT_ADDR_E_offs-CS_BLIT_base
block_ADDR_D_MIN_offs		:=	CS_BLIT_ADDR_D_MIN_offs-CS_BLIT_base
block_ADDR_D_MAX_offs		:=	CS_BLIT_ADDR_D_MAX_offs-CS_BLIT_base
block_STRIDE_D_offs			:=	CS_BLIT_STRIDE_D_offs-CS_BLIT_base
block_SHIFT_B_offs			:=	CS_BLIT_SHIFT_B_offs-CS_BLIT_base
block_ADDR_D_offs			:=	CS_BLIT_ADDR_D_offs-CS_BLIT_base


		.import _blit_ctl_full, _blit_ctl_full_updE, _blit_copy, _blit_plot_masked, _blit_ctl_full_noExec
