
#include "layout.h"
#include "hw.h"
#include "hardware.h"
#include <string.h>
#include "debug.h"

romloc c20k_romset[] = {
	{0x0, 0x7E00, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM},
	{0x1, 0x9E00, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},
	{0x2, 0x7E40, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM},
	{0x3, 0x9E40, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},
	{0x4, 0x7E80, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM},
	{0x5, 0x9E80, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},
	{0x6, 0x7EC0, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM},
	{0x7, 0x9EC0, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},
	{0x8, 0x7F00, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM|ROMLOC_FLAGS_MOS|ROMLOC_FLAGS_PREBOOT},
	{0x9, 0x9F00, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH|ROMLOC_FLAGS_MOS},
	{0xA, 0x7F40, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM},
	{0xB, 0x9F40, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},
	{0xC, 0x7F80, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM},
	{0xD, 0x9F80, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},
	{0xE, 0x1F00, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_BBRAM|ROMLOC_FLAGS_PREBOOT},
	{0xF, 0x9FC0, ROMLOC_FLAGS_MAP0|ROMLOC_FLAGS_FLASH},

	{0x0, 0x7C00, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0x1, 0x9C00, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},
	{0x2, 0x7C40, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0x3, 0x9C40, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},
	{0x4, 0x7C80, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0x5, 0x9C80, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},
	{0x6, 0x7CC0, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0x7, 0x9CC0, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},
	{0x8, 0x7D00, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM|ROMLOC_FLAGS_MOS},
	{0x9, 0x9D00, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH|ROMLOC_FLAGS_MOS},
	{0xA, 0x7D40, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0xB, 0x9D40, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},
	{0xC, 0x7D80, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0xD, 0x9D80, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},
	{0xE, 0x1F40, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_BBRAM},
	{0xF, 0x9DC0, ROMLOC_FLAGS_MAP1|ROMLOC_FLAGS_FLASH},

	{0, 0, 0}
};


//TODO: detect at boot
romloc *cur_romset  = &c20k_romset[0];

//These assume running in MOS area so we are safe to tickle the Flash EEPROM
bool erase_slot(romloc *rl) {
	unsigned short page;
	unsigned short pagectr;
	if ((rl->flags & ROMLOC_FLAGS_FLASH)!=0) {
		return 0;
	} else {
		page = rl->page;
		pagectr = 0;
		while (pagectr < 0x40) {
			jim_page(page);

			debug_printf("E:%04X\n", (long)page);
			memset((void *)JIM, 0xFF, 0x100);

			page++;
			pagectr++;
		}
		debug_printf("E:OK\n");
		return 1;
	}

}